### ISSUE TITLE
Trouble using the docker-compose.yml

### ISSUE THREAD

**Issue by LandonStewart** [oasis-open/cti-taxii-server#140]
I just want to spin this up and do a simple `print(server.title)` with the client.

The problem is shown at the bottom of the outputs below.

### Build it:
_Note: `docker build . -t medallion` gave me an error related to buildkit but I noticed there's `build:` stuff in the docker-compose.yml so I tried using that._

```
$ docker-compose build
mongo uses an image, skipping
mongo-express uses an image, skipping
Building medallion
Step 1/5 : FROM python:alpine
 ---> 85987b1a8b9d
Step 2/5 : COPY . /opt/taxii
 ---> d8e1eb658bf3
Step 3/5 : COPY ./docker_utils/*.json /opt/taxii
 ---> 30dd9f78e25d
Step 4/5 : WORKDIR /opt/taxii
 ---> Running in bb52137df115
Removing intermediate container bb52137df115
 ---> 536e29143642
Step 5/5 : RUN pip install --upgrade pip setuptools     && pip install pymongo     && pip install .
 ---> Running in a7c735b6f14a
Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.0.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (53.0.0)
Collecting pymongo
  Downloading pymongo-3.11.3.tar.gz (777 kB)
Building wheels for collected packages: pymongo
  Building wheel for pymongo (setup.py): started
  Building wheel for pymongo (setup.py): finished with status 'done'
  Created wheel for pymongo: filename=pymongo-3.11.3-cp39-cp39-linux_x86_64.whl size=345368 sha256=6f53e62c906a77dbd7cf2d3ca44c2c498b2bbbefd4b1f47a77fab6752b45bde7
  Stored in directory: /root/.cache/pip/wheels/79/2c/e8/e0b7ff462995c6e207647a7922cafc3275d3eb23dc99eda79a
Successfully built pymongo
Installing collected packages: pymongo
Successfully installed pymongo-3.11.3
Processing /opt/taxii
Collecting flask>=0.12.1
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
Collecting Flask-HTTPAuth
  Downloading Flask_HTTPAuth-4.2.0-py2.py3-none-any.whl (5.9 kB)
Collecting pytz
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting six
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting click>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
Building wheels for collected packages: medallion, MarkupSafe
  Building wheel for medallion (setup.py): started
  Building wheel for medallion (setup.py): finished with status 'done'
  Created wheel for medallion: filename=medallion-3.0.0-py2.py3-none-any.whl size=31808 sha256=d60b21016c3ee4dfebe9beb7bd194652548ac7029d9d68653471ad83f1d0cee0
  Stored in directory: /tmp/pip-ephem-wheel-cache-a7vfyz9o/wheels/98/51/02/41268970b3da93cd0d5ee2b7b0e60ba6c6be9f6b6d4b912826
  Building wheel for MarkupSafe (setup.py): started
  Building wheel for MarkupSafe (setup.py): finished with status 'done'
  Created wheel for MarkupSafe: filename=MarkupSafe-1.1.1-py3-none-any.whl size=12629 sha256=ef8aedc3ae51239aeca958d25ed7c90726c66d5e6e5a1797136062dd4e36abc0
  Stored in directory: /root/.cache/pip/wheels/e0/19/6f/6ba857621f50dc08e084312746ed3ebc14211ba30037d5e44e
Successfully built medallion MarkupSafe
Installing collected packages: MarkupSafe, Werkzeug, Jinja2, itsdangerous, click, flask, six, pytz, Flask-HTTPAuth, medallion
Successfully installed Flask-HTTPAuth-4.2.0 Jinja2-2.11.3 MarkupSafe-1.1.1 Werkzeug-1.0.1 click-7.1.2 flask-1.1.2 itsdangerous-1.1.0 medallion-3.0.0 pytz-2021.1 six-1.15.0
Removing intermediate container a7c735b6f14a
 ---> 6e5dc5b07a7d

Successfully built 6e5dc5b07a7d
Successfully tagged cti-taxii-server_medallion:latest
```

### Run it:
```
$ docker-compose up -d
Creating network "cti-taxii-server_default" with the default driver
Creating mongo     ... done
Creating medallion ... done
Creating mongo-express ... done
```

### Use it (error):
```
$ python
Python 3.8.6 (default, Nov 20 2020, 18:29:40) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from taxii2client.v21 import Server
>>> server = Server('http://localhost:5000/taxii2', user='admin', password='Password0')
>>> print(server.title)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/<myusername>/Projects/cti-taxii-server/.venv/lib/python3.8/site-packages/taxii2client/v21/__init__.py", line 632, in title
    self._ensure_loaded()
  File "/Users/<myusername>/Projects/cti-taxii-server/.venv/lib/python3.8/site-packages/taxii2client/v21/__init__.py", line 668, in _ensure_loaded
    self.refresh()
  File "/Users/<myusername>/Projects/cti-taxii-server/.venv/lib/python3.8/site-packages/taxii2client/v21/__init__.py", line 705, in refresh
    response = self.__raw = self._conn.get(self.url)
  File "/Users/<myusername>/Projects/cti-taxii-server/.venv/lib/python3.8/site-packages/taxii2client/common.py", line 309, in get
    raise e
  File "/Users/<myusername>/Projects/cti-taxii-server/.venv/lib/python3.8/site-packages/taxii2client/common.py", line 299, in get
    resp.raise_for_status()
  File "/Users/<myusername>/Projects/cti-taxii-server/.venv/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:5000/taxii2/
```

**Comment by LandonStewart** [comment]
Additionally the docker logs show that the Mongo connection was successful but there was an exception from medallion.

```
mongo            | {"t":{"$date":"2021-02-05T21:27:29.314+00:00"},"s":"I",  "c":"NETWORK",  "id":22943,   "ctx":"listener","msg":"Connection accepted","attr":{"remote":"172.31.0.3:54702","connectionId":6,"connectionCount":5}}
mongo            | {"t":{"$date":"2021-02-05T21:27:29.315+00:00"},"s":"I",  "c":"NETWORK",  "id":51800,   "ctx":"conn6","msg":"client metadata","attr":{"remote":"172.31.0.3:54702","client":"conn6","doc":{"driver":{"name":"PyMongo","version":"3.11.3"},"os":{"type":"Linux","name":"Linux","architecture":"x86_64","version":"4.19.121-linuxkit"},"platform":"CPython 3.9.1.final.0"}}}
mongo            | {"t":{"$date":"2021-02-05T21:27:29.328+00:00"},"s":"I",  "c":"ACCESS",   "id":20250,   "ctx":"conn6","msg":"Successful authentication","attr":{"mechanism":"SCRAM-SHA-256","principalName":"root","authenticationDatabase":"admin","client":"172.31.0.3:54702"}}
medallion        | [medallion] [ERROR   ] [2021-02-05 21:36:21,179] Exception on /taxii2/ [GET]
medallion        | Traceback (most recent call last):
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
medallion        |     response = self.full_dispatch_request()
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
medallion        |     rv = self.handle_user_exception(e)
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
medallion        |     reraise(exc_type, exc_value, tb)
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
medallion        |     raise value
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
medallion        |     rv = self.dispatch_request()
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
medallion        |     return self.view_functions[rule.endpoint](**req.view_args)
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask_httpauth.py", line 164, in decorated
medallion        |     return f(*args, **kwargs)
medallion        |   File "/usr/local/lib/python3.9/site-packages/medallion/views/discovery.py", line 32, in get_server_discovery
medallion        |     server_discovery = current_app.medallion_backend.server_discovery()
medallion        |   File "/usr/local/lib/python3.9/site-packages/medallion/backends/mongodb_backend.py", line 27, in api_wrapper
medallion        |     return func(*args, **kwargs)
medallion        |   File "/usr/local/lib/python3.9/site-packages/medallion/backends/mongodb_backend.py", line 164, in server_discovery
medallion        |     info = discovery_info.aggregate(pipeline).next()
medallion        |   File "/usr/local/lib/python3.9/site-packages/pymongo/command_cursor.py", line 263, in next
medallion        |     raise StopIteration
medallion        | StopIteration
medallion        | 172.31.0.1 - - [05/Feb/2021 21:36:21] "GET /taxii2/ HTTP/1.1" 500 -
medallion        | Error on request:
medallion        | Traceback (most recent call last):
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
medallion        |     response = self.full_dispatch_request()
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
medallion        |     rv = self.handle_user_exception(e)
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
medallion        |     reraise(exc_type, exc_value, tb)
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
medallion        |     raise value
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
medallion        |     rv = self.dispatch_request()
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
medallion        |     return self.view_functions[rule.endpoint](**req.view_args)
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask_httpauth.py", line 164, in decorated
medallion        |     return f(*args, **kwargs)
medallion        |   File "/usr/local/lib/python3.9/site-packages/medallion/views/discovery.py", line 32, in get_server_discovery
medallion        |     server_discovery = current_app.medallion_backend.server_discovery()
medallion        |   File "/usr/local/lib/python3.9/site-packages/medallion/backends/mongodb_backend.py", line 27, in api_wrapper
medallion        |     return func(*args, **kwargs)
medallion        |   File "/usr/local/lib/python3.9/site-packages/medallion/backends/mongodb_backend.py", line 164, in server_discovery
medallion        |     info = discovery_info.aggregate(pipeline).next()
medallion        |   File "/usr/local/lib/python3.9/site-packages/pymongo/command_cursor.py", line 263, in next
medallion        |     raise StopIteration
medallion        | StopIteration
medallion        | 
medallion        | During handling of the above exception, another exception occurred:
medallion        | 
medallion        | Traceback (most recent call last):
medallion        |   File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 323, in run_wsgi
medallion        |     execute(self.server.app)
medallion        |   File "/usr/local/lib/python3.9/site-packages/werkzeug/serving.py", line 312, in execute
medallion        |     application_iter = app(environ, start_response)
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
medallion        |     return self.wsgi_app(environ, start_response)
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
medallion        |     response = self.handle_exception(e)
medallion        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1879, in handle_exception
medallion        |     server_error = handler(server_error)
medallion        |   File "/usr/local/lib/python3.9/site-packages/medallion/__init__.py", line 138, in handle_error
medallion        |     "description": str(error.args[0]),
medallion        | IndexError: tuple index out of range
```

**Comment by emmanvg** [comment]
Hi @LandonStewart sorry for the delay in this response... there is an additional step that needs to be done in order for the `medallion` TAXII Server to respond to requests. The error you are seeing now is due to the backend (MongoDB) being empty and the code attempting to run as normal. The steps to for you to follow:

1.) Make sure the Docker instances are running
2.) Run the initialization script (this will add dummy initialization data like the Server Discovery, API Root, Collections, and some STIX Objects).
3.) Re-try the script you had written from the client library

```
C:\cti-taxii-server> docker-compose up -d
C:\cti-taxii-server> python medallion\test\data\initialize_mongodb.py
```

What type of request can I make to check if it worked?
- You can request the Server Discovery
``` python
from taxii2client.v21 import Server
server = Server('http://localhost:5000/taxii2', user='admin', password='Password0')
print(server.title)
```
- You can request some Objects
``` python
from taxii2client.v21 import Collection
collection = Collection('http://localhost:5000/trustgroup1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/', user='admin', password='Password0')
print(collection.get_objects())
```

Hope this helps!

On our end, we identified the following changes:
- [ ] Provide an error response if the Backend is uninitialized (empty).
- [ ] Check if we can automate initializing the backend with dummy data, otherwise add the additional step in the repo documentation.

**Comment by clenk** [comment]
I'm closing this for now, but please reopen or make a new issue if this didn't help.
