### ISSUE TITLE
TAXII Specification compliance for 'timestamp' datatypes on 'added_after' filters

### ISSUE THREAD

**Issue by ahpearce** [oasis-open/cti-taxii-server#35]
I'm encountering this error when attempting to perform a GET on the objects endpoint, filtering with the `?added_after=2018-06-29T12:58:28-04:00` query parameter.

I did some digging into `strptime` and the TAXII spec. The above timestamp _should_ be considered valid. 

> The timestamp field MUST be a valid RFC 3339-formatted timestamp [RFC3339] using the format YYYY-MM-DDTHH:mm:ss.[s+]Z where the “s+” represents 1 or more sub-second values. **The brackets denote that sub-second precision is optional, and that if no digits are provided, the decimal place MUST NOT be present.**

It appears in `utils` there is a `common.py` with a method for handling this type of thing, but it isn't used in a few cases. Not sure if it's feasible to replace all calls to `datetime.strptime()` with the util method?

Here is the full traceback.
```
[2018-06-29 13:07:14,392] ERROR in app: Exception on /trustgroup1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/objects/ [GET]
Traceback (most recent call last):
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/medallion/utils/common.py", line 101, in convert_to_stix_datetime
    return dt.datetime.strptime(timestamp_string, "%Y-%m-%dT%H:%M:%S.%fZ")
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-06-29T12:58:28-04:00' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/flask_httpauth.py", line 104, in decorated
    return f(*args, **kwargs)
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/medallion/views/objects.py", line 28, in get_or_add_objects
    objects = current_app.medallion_backend.get_objects(api_root, id_, request.args, ("id", "type", "version"))
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/medallion/backends/mongodb_backend.py", line 128, in get_objects
    {"mongodb_collection": api_root_db["manifests"], "_collection_id": id_}
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/medallion/filters/mongodb_filter.py", line 48, in process_filter
    added_after_timestamp = common.convert_to_stix_datetime(added_after_date)
  File "/Users/user/envs/mockweb/lib/python3.6/site-packages/medallion/utils/common.py", line 103, in convert_to_stix_datetime
    return dt.datetime.strptime(timestamp_string, "%Y-%m-%dT%H:%M:%SZ")
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data '2018-06-29T12:58:28-04:00' does not match format '%Y-%m-%dT%H:%M:%SZ'
127.0.0.1 - - [29/Jun/2018 13:07:14] "GET /trustgroup1/collections/91a7b528-80eb-42ed-a74d-c6fbd5a26116/objects/?added_after=2018-06-29T12:58:28-04:00 HTTP/1.1" 500 -

```

**Comment by gtback** [comment]
Hi, @ahpearce . Thanks for creating this issue.

The TAXII `timestamp` datatype (which is used for the `added_after` query parameter must be in UTC and use `Z` as the offset. `-04:00` is not valid:

> The timestamp **MUST** be represented in the UTC timezone and **MUST** use the “Z” designation to indicate this.

[TAXII 2.0 specification](http://docs.oasis-open.org/cti/taxii/v2.0/cs01/taxii-v2.0-cs01.html#_Toc496542710)
 
The only date/time-related functions in `utils/common.py` are:
- `get_timestamp` for returning the current time
- `format_datetime` for converting a `datetime` object to the correct UTC string representation
- `convert_to_stix_datetime` which uses `strptime` to parse a valid UTC date/time string to a `datetime` object. This is where the traceback you posted is coming from, so I'm not sure what you mean by "replacing calls to `datetime.strptime()` with the util method."

**Comment by gtback** [comment]
@ahpearce, I think the server is already doing the right thing, but if not, please re-open and let me know what I missed. Thanks again!

**Comment by ahpearce** [comment]
Wow! I completely overlooked the bullet right below the one I posted; thanks for sharing. I thought this had to do with the precision of the %f operator in the date format calls, but this makes a lot more sense. Thanks!

**Comment by gtback** [comment]
Thanks, @ahpearce, happy to help! If you run into any other unexpected behavior, please let us know 😁 .
