### ISSUE TITLE
Bug: error adding STIX2 bundle via cti-taxii-client #bug

### ISSUE THREAD

**Issue by davidonzo** [oasis-open/cti-taxii-server#50]
Adding STIX bundle via "cti-taxii-client", the server returns http error code 500.

```
[17/May/2019 10:10:25] "POST /info/collections/c0616fa4-fa24-4bb7-91d7-4ebb13a176b2/objects/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_httpauth.py", line 104, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/medallion/views/objects.py", line 50, in get_or_add_objects
    status = current_app.medallion_backend.add_objects(api_root, id_, request.get_json(force=True), request_time)
  File "/usr/local/lib/python3.5/dist-packages/medallion/backends/memory_backend.py", line 191, in add_objects
    api_info["status"].append(status)
AttributeError: 'dict' object has no attribute 'append'
```

Proposed a bugfix as poll request [#49](https://github.com/oasis-open/cti-taxii-server/pull/49)
Hope this help.

**Comment by emmanvg** [comment]
@davidonzo thanks for spotting this issue. We have looked into it and it seems like there is an issue with the default_data.json structure. The `"status"` as we  use it here is meant to be a **list of `status` resource objects** as defined in the spec. You can look at the other api_root data and confirm is meant to be a list. Also, if you have defined any new ones for other purposes make sure you use a list for it. Personally, I don't think we need the PR you created.

- The error is here: https://github.com/oasis-open/cti-taxii-server/blob/master/medallion/test/data/default_data.json#L22-L24

**Comment by emmanvg** [comment]
@davidonzo I have closed the issue as I think this was only a problem with our sample json we include with the library. If you think this is not the case, feel free to reopen.
